### ISSUE TITLE
Regarding your data camp course

### ISSUE THREAD

**Issue by psomdeb25** [filipsch/filipsch.github.io#1]
Hello Filip,

Your course on intermediate R was really interesting and I learnt a lot from you course. I took up the course because I needed to learn some R before taking up my statistics course, part of my Masters curriculum. It is really helping me a lot. Now I am learning the course on ggplot2 functions on DataCamp. Do you have any Capstone Projects for R programming language that I could be involved in?

It was a wonderful time learning from you!

Thanks!

Somdeb Paul
M.Sc Genome Science and Technology
University of British Columbia

**Comment by filipsch** [comment]
Hi,

Thanks for the kind words!
Soon, we'll be starting with R practice interfaces and R assessments on DataCamp.

Stay tuned!

Filip
